baseurl = "/"
languageCode = "en-us"
title = "tideyzhang"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true


[permalinks]
    post = "/:year/:month/:day/:title/"



[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "收集"
    url = "/collection/"
    weight = 3
[[menu.main]]
    name = "推荐"
    url = "/havefun/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    description = "Ivy."
    footer = "&copy; [tideyzhang](https://tideyzhang.me)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "python"]
  highlightjsTheme = "github"
